### ISSUE TITLE
Remove androidx.work.impl.WorkManagerInitializer from your AndroidManifest.xml

### ISSUE THREAD

**Issue by Bubu** [vector-im/riotX-android#1012]
```
> Task :vector:lintVitalFdroidRelease
/home/bubu/projects/oss/fdroiddata/build/im.vector.riotx/vector: Error: Remove androidx.work.impl.WorkManagerInitializer from your AndroidManifest.xml when using on-demand initialization. [RemoveWorkManagerInitializer]

   Explanation for issues of type "RemoveWorkManagerInitializer":
   If an android.app.Application implements
   androidx.work.Configuration.Provider,
   the default androidx.work.impl.WorkManagerInitializer needs to be removed
   from the
   AndroidManifest.xml file.

1 errors, 0 warnings

> Task :vector:lintVitalFdroidRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vector:lintVitalFdroidRelease'.
> Lint found fatal errors while assembling a release target.
  
  To proceed, either fix the issues identified by lint, or modify your build script as follows:
  ...
  android {
      lintOptions {
          checkReleaseBuilds false
          // Or, if you prefer, you can continue to check for errors in release builds,
          // but continue the build even when errors are found:
          abortOnError false
      }
  }
  ...

```

**Comment by bmarty** [comment]
The new lint check has been added in [work 2.3.0-beta02](https://developer.android.com/jetpack/androidx/releases/work#2.3.0-beta02)

And the lib has been updated to this version in RiotX since the [6th of January](99c523b710bec38d3ce80515530925761cb1c6e5), which can explain why you see the lint error now (but why not in the previous release?).

`./gradlew assembleFdroidRelease` does not fail for me, and the task `lintVitalFdroidRelease` is ok on my side.
The issue reported by `lintVitalFdroidRelease` in your case seems like a false positive because the code in the SDK ensure that the node is removed from the built application (see https://github.com/vector-im/riotX-android/blob/859c75df983b085825cab9c1e6f00032abb06813/matrix-sdk-android/src/main/AndroidManifest.xml#L15)

**Comment by Bubu** [comment]
> but why not in the previous release?

I was on vacation :-)

I'll disable the lint check for this version then, I've no idea why you don't see it.
One thing that f-droid does differently then when you build normally is that it starts from a clean git repo checkout (`git clean -df`) which I think is far more thorough than `gradle clean`.

**Comment by bmarty** [comment]
The CI, AFIK do a git clone before building the application, but I may be wrong

Maybe

```
<provider
    android:name="androidx.work.impl.WorkManagerInitializer"
    android:authorities="${applicationId}.workmanager-init"
    tools:node="remove" />
```

has to be done in the app and not only in the Matrix SDK.
To be honest I wanted to get the same lint error has you before fixing the issue

**Comment by okias** [comment]
@Bubu does build work for you now?

**Comment by Bubu** [comment]
I works with this: https://github.com/f-droid/fdroiddata/commit/5c02375034e5e9ae324c6f4993bce77f18565981

**Comment by Bubu** [comment]
I think this is long solved.

**Comment by bmarty** [comment]
It is not yet, but you have removed the lint check on your build chain :).
We have the same error now and we will have to fix. For the moment, I have added `abortOnError false` as a quick fix, but this is not ideal.
