### ISSUE TITLE
Illegible controls on bottom of the screen

### ISSUE THREAD

**Issue by David-Else** [vector-im/riotX-android#1189]
This is what I see on Android 6.01 riotx v0.18.1:
![Screenshot_20200328-171005 png](https://user-images.githubusercontent.com/12832280/77829093-a1258a80-7117-11ea-8071-e9a99287b849.jpg)

It looks better here than on the actual screen, you have to stare really hard to notice the three icons are there, I assume this is a bug. It is meant to be white on black like every other app.

**Comment by Porkepix** [comment]
Same issue here, same version of Android : Android Marshmallow, 6.0.1 on Sony unmodified ROM.
Issue with this specific version of Android?
Riot (without the X) does not have the issue.

**Comment by cron410** [comment]
I don't have this issue on Android 10 so it must be related to how older versions of Android pull color from the app to adjust the navbar. Have you tried the RiotX Dark or Black theme? There also might be a way to change what color the navbar uses in Android settings. Another option is to install "Navbar Apps" from your app store. I used this in the past to override the navbar color on an Android device that did not allow me to specify a static color. https://play.google.com/store/apps/details?id=pl.damianpiwowarski.navbarapps&hl=en

**Comment by Porkepix** [comment]
> I don't have this issue on Android 10 so it must be related to how older versions of Android pull color from the app to adjust the navbar. Have you tried the RiotX Dark or Black theme?

Issue is only with the defaul theme.

# There also might be a way to change what color the navbar uses in Android settings. Another option is to install "Navbar Apps" from your app store. I used this in the past to override the navbar color on an Android device that did not allow me to specify a static color. https://play.google.com/store/apps/details?id=pl.damianpiwowarski.navbarapps&hl=en

There shouldn't have any need to tinker within system's settings for that. RiotX is the only application I know to have such kind of issues, even Riot doesn't have this issue, so that's within RiotX that it should be fixed.

**Comment by bmarty** [comment]
Fixed in #1450 (Also see #1342), available in RiotX 0.22.0
