### ISSUE TITLE
Hide redacted message in local echo

### ISSUE THREAD

**Issue by lub** [vector-im/riotX-android#1385]
#1370 introduced the option to hide redacted messages completely.

It seems when you redact a message the placeholder is still displayed until you switch rooms.

In riot-web the message disappears completely.

Steps to reproduce:
- enable hiding redaction placeholders
- send a message
- redact a message

(build F-b2658)

**Comment by bmarty** [comment]
Hi @lub ,

Yes, I've noticed that when implementing #1370. So it can be considered as a bug, but to be honest, I think it's quite interesting to have a temporary local echo of the message deletion. That's why I did not investigate that (due to the cache invalidation somewhere).

Don't you agree with me?

**Comment by lub** [comment]
I agree it's really insteresting and imo it can stay that way. Just wanted to point out, that currently it's inconsistent with e.g. riot-web (I don't know what riot-ios does), so it seemed a bit off.

**Comment by bmarty** [comment]
Cool! Thanks
