### ISSUE TITLE
attachments list doesn't work in e2ee rooms

### ISSUE THREAD

**Issue by lub** [vector-im/riotX-android#1405]
It just displays

> There are no media in this room
> There are no files in this room

**Comment by bmarty** [comment]
Thanks for reporting, it was working, but it's not anymore. Let me check that.

**Comment by bmarty** [comment]
Actually it's not working on Riot-Web as well, which is normal, the homeserver cannot return event containing an url because it does not have access to the event content because of encryption.
We should be able to display the image we have in cached decrypted event though, which is bigger to implement than a small fix.

**Comment by lub** [comment]
Actually in riot-web it works for me, but maybe it also uses the seshat index or pulls all events in the cache during indexing?
