### ISSUE TITLE
White text on light theme

### ISSUE THREAD

**Issue by elegaanz** [vector-im/riotX-android#1511]
Hello, 

When choosing the light theme in the settings, the color of the text stays white, at least for the content of messages. It makes it impossible to read any message. 

![Screenshot_2020-06-20-09-40-02-732_im vector riotx](https://user-images.githubusercontent.com/16254623/85196353-0bdf0000-b2da-11ea-83c8-c40c23322f3d.jpg)

The status.im has a little bit more contrast, but not enough to read either.

**Comment by elegaanz** [comment]
After setting my phone's theme to light instead of dark (in the global phone settings, not just in RiotX), the problem seems to be fixed. Should I close or keep this open?

**Comment by TR-SLimey** [comment]
I'm not part of the dev team, but I think you should probably keep it open since this should not happen regardless of what theme is set on your phone. It seems like RiotX takes the font colour from the global Android settings but the colour of everything else from RiotX settings which is probably a bug.

**Comment by bmarty** [comment]
The issue has been fixed in 0.22.0. Are you using this version?

**Comment by elegaanz** [comment]
I updated a few days ago, and it seems to be fixed now. Thank you.
