### ISSUE TITLE
Support homeserver discovery from MXID

### ISSUE THREAD

**Issue by dkasak** [vector-im/riotX-android#476]
When the full MXID is entered as the username, RiotX should try to do a homeserver discovery (via well-known) and fill the homeserver URL field correspondigly if the discovery was successful.

**Comment by bmarty** [comment]
This is not possible any more with the new sign in flow.
You have to select the homeserver first, then you can enter your userId.
We could add an advanced sign in mode when user could be prompted to enter a full mxid, but it will not be implemented by the core team now.
I keep the issue opened for this idea.

**Comment by cyphar** [comment]
I also agree this should be something that is supported, because MXIDs are something that all existing users are familiar with, and new users will see when they have to ping other people in a room (or tell someone their account name to start a direct chat).

I do understand why the new login flow exists (and in fairness, it is much cleaner than the original Riot one), but given that users will need to log in much more often than they sign up for a new account, there really should be a "login with *user-friendly term for MXID*" button that allows you to just type `@cyphar:cyphar.com` and log in.

**Comment by deepbluev7** [comment]
So I just hit this too. Showing someone how to login via RiotX is a really bad experience. The login screen, where you enter your credentials, should be the first hing presented to the user. Only if server lookup fails, it should prompt for the server. Basically the credentials input should just be moved forward in the flow.

**Comment by olmari** [comment]
Plussed this one, kind of "essential" feature to ease end user workload. While current (0.17.0) custom server settings can still be there and is maybe even needed, it should be either advanced or after failure of auto-discovery...

Suggestion: for login, ask user full MXID, try fetch, if fail, then ask questions as it does now :)
