### ISSUE TITLE
reply have bad syntax

### ISSUE THREAD

**Issue by progserega** [vector-im/riotX-android#551]
when use reply for text in RiotX I get "formatted_body" in event:
`"formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!rOaKdLhyhejwoZiVAX:rsprim.ru/$156811358612871pqZqW:rsprim.ru\">В ответ на</a><a href=\"https://matrix.to/#/@vk2matrix:rsprim.ru\">@vk2matrix:rsprim.ru</a><br />test</blockquote></mx-reply>reply_text"
`

When I reply in Riot-Web, I get "formatted_body" in event:
`"formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!rOaKdLhyhejwoZiVAX:rsprim.ru/$156811358612871pqZqW:rsprim.ru?via=rsprim.ru\">In reply to</a> <a href=\"https://matrix.to/#/@vk2matrix:rsprim.ru\">@vk2matrix:rsprim.ru</a><br>test</blockquote></mx-reply>reply_text",`

So, Riot-web post: `...</a><br>test</blockquote>...`
But RiotX post: `...</a><br />test</blockquote>...` - tag `<br>` not equal.

I found this when remove markdown synatax for bridge events to another IM-network. I think that syntax must be equal.

**Comment by tulir** [comment]
I don't think this should be changed. Both are valid HTML.

@progserega you should be removing the reply fallback entirely rather than parsing it at all. Just remove everything inside `mx-reply` tags, then get the original event directly from the server. If you must parse it, use a real HTML parser instead of whatever hacky string matching you currently have.

**Comment by progserega** [comment]
ok. Bug can be close.
