### ISSUE TITLE
Well-known lookup for homeserver url

### ISSUE THREAD

**Issue by jaywink** [vector-im/riotX-android#778]
If my Synapse is hosted at `https://matrix.example.com` but my Synapse server name is `https://example.com`, typing `https://example.com` into the server URL should do a well-known lookup as per hhttps://matrix.org/docs/spec/client_server/r0.6.0#server-discovery

Related to but separate from #476

**Comment by aaronraimist** [comment]
> typing https://example.com into the server URL should do a well-known lookup as per hhttps://matrix.org/docs/spec/client_server/r0.6.0#server-discovery

@jaywink the spec does not say that (which is why Riot Web has refused to implement this)

**Comment by cyphar** [comment]
This issue is that matrix IDs aren't a supported login method with RiotX (see #476). If they were, then RiotX would have to implement the auto-discovery as described in the spec.

But the key thing to keep in mind with this issue is that right now, non-technical users who know their MXID is `@foobar:somehomeserver.com` would have to figure out that the real homeserver URL is `matrix.somehomeserver.com` or `matrix.node-ABC.somehomeserver.com`.

Given that RiotX is meant to make things easier-to-use, I find it odd that the very first thing a user needs to use (the login flow) is now more complicated if their account is on a non-`matrix.org` homeserver.

**Comment by aaronraimist** [comment]
Yeah. The comment I made in `#riotx:matrix.org` before I went searching for issues was

> Is the current login flow pretty early still or is this close to the final design?

> I think the login flow should emphasize entering your full username and having the .well-known lookup done rather than entering the homeserver URL which should be a more advanced/last resort feature.

https://github.com/vector-im/riotX-android/issues/476 is what the login screen should be, with like a tiny little option at the bottom to enter the homeserver URL for the one homeserver out there that doesn't have .well-known.

Since the spec says you can't do a well-known lookup on an explicitly entered homeserver URL we should be training users to always enter their full MXID and then they never need to know anything about the homeserver URL.

**Comment by aaronraimist** [comment]
RiotX has implemented this now even though other Riots have not done so. A decision needs to be made so all clients implement it in the same way, otherwise it is confusing for users.

**Comment by bmarty** [comment]
Yes, it's now implemented on RiotX. Also Well-known (with userId) support well be re-activated very soon.

**Comment by mrSaT13** [comment]
Good day I understood correctly, if well.if it is not on the server, then let's say in the last Element application I get the error can I use the full user and password indexer?- and there will be no well ,know error?
