### ISSUE TITLE
Failed to encrypt message in room (message stays in red)

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#925]
Can be fixed by clearing cache
Need to investigate how it can happen
(IN this case it's a dm other federation, with a slow one)

https://riot.im/bugreports/listing/2020-02-01/120437/logs-0000.log.gz

## encryptEventContent() : Unable to encrypt Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.

**Comment by barudaret** [comment]
I've had ones that don't resolve themselves when I clear cache.

**Comment by ZerataX** [comment]
seemed like it didn't work for me in any room with a black shield

**Comment by BillCarsonFr** [comment]
I had this error again a few times
always the same log 
> encryptEventContent() : Unable to encrypt Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.

**Comment by BillCarsonFr** [comment]
https://riot.im/bugreports/listing/2020-02-26/160613/

**Comment by pwr22** [comment]
> 
> 
> I've had ones that don't resolve themselves when I clear cache.

I seem to have this.

**Comment by BillCarsonFr** [comment]
-> https://riot.im/bugreports/listing/2020-04-03/100612/

**Comment by pwr22** [comment]
I signed out, nuked cache and storage and now it works after signing back in anew.

**Comment by NHAS** [comment]
The only way I solved this for me was to sign out, uninstall element and reinstall. Just logging out resulted in the application crashing on startup.

**Comment by vetko** [comment]
I had the same issue previous week, **it's fixed now**, but might help the devs debug/understand the root cause:
- 2 matrix users, both of them with android and web/desktop clients
- both participating in a DM room with each other
- at some moment, android for user 1 was not able to send encrypted messages anymore (web/desktop clients work)
- after resetting that android client for user 1, the error miraculously "jumped" to user 2's android, which started to be not able to send encrypted messages anymore
- after resetting user 2's android, the issue jumped back to user 1's android, and so forth...

Up until the point we realized, that one of the desktop clients (of user 1) was **outdated** (I think it was 1.7.33, instead of 1.7.34 which is the latest at the moment).
After getting rid of that client (and resetting both android clients again), the communication works again flawlessly since.

**Comment by egtann** [comment]
I ran into this issue. Messages in a 1-to-1 encrypted conversation wouldn't send from my Android (Pixel 4) device. Clearing cache did not fix it. I logged out, uninstalled and reinstalled element and was able to send messages again.

This is OK for technical users who can search GitHub but is a showstopper for non-technical users.

**Comment by forever8361** [comment]
> 我遇到了这个问题。一对一加密对话中的消息突然无法从我最新的 Android (Pixel 4) 设备发送。清除缓存并没有解决它。我注销，卸载并重新安装了元素，并且能够再次发送消息。
> 
> 这对于可以搜索 GitHub 的技术用户来说是可以的，但对于非技术用户来说却是一个阻碍。

I have the same problem, but after logging out, uninstalling, installing and logging in, it still doesn't work
